general:
  exclude:
    - "\\.git.*"
    - "\\.(yml|md|txt)"
    - "^\\.ci.*"
    - "\\.(m4|ac)"
    - "LICENSE"
    - "debian/copyright"
    - "debian/compat"
    - "debian/source/format"

bsd:
  validate-spdx-license: true
  include:
    - ".*\\.(am|in|hpp|cpp|py|cc|h|c|sh)$"
