#!/bin/bash -eE
# Wrapper to add correct parameters to the main app
TEST_DEV=$(ibdev2netdev | awk '{ print $1 }' ):1
export MXM_RDMA_PORTS="${TEST_DEV}"
export HCOLL_MAIN_IB="${TEST_DEV}"
/usr/bin/taskset "${@}"
